#!/bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Suspend\n  Hibernate\n󰍃  Log Out\n  Lock" | rofi -dmenu -i -theme-str '@import "config.rasi"')

case "$chosen" in
	"  Power Off") systemctl poweroff ;;
	"  Restart") systemctl reboot ;;
	"  Suspend") systemctl suspend ;;
	"  Hibernate") systemctl hibernate ;;
	"󰍃  Log Out") loginctl kill-session "$whoami" ;;
	"  Lock") i3lock ;;
	*) exit 1 ;;
esac
